### ISSUE TITLE
Apple Silicon architecture compatibility

### ISSUE THREAD

**Issue by iraszl** [bumi/lnrpc#13]
I wonder if this gem would work on an M1 mac?

**Comment by bumi** [comment]
do you have a stracktrace? and can you check that your project uses recent grpc and google-protobuf versions.

**Comment by iraszl** [comment]
Sorry, I will have to research what you're asking before I can give you an answer...

**Comment by iraszl** [comment]
This is the basic ruby app:
```
require "lnrpc"
credentials = File.read("tls.cert")
macaroon = File.read("admin.macaroon").unpack("H*")
client = Lnrpc::Lightning::Stub.new("localhost:10009", GRPC::Core::ChannelCredentials.new(self.credentials))
request = Lnrpc::GetInfoRequest.new
response = client.get_info(request, { metadata: { macaroon: macaroon } }) #=> Lnrpc::GetInfoResponse
puts response.alias
```

This is the error I'm getting:
```
<internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle, 9): no suitable image found.  Did find: (LoadError)
        /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle: mach-o, but wrong architecture
        /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle: mach-o, but wrong architecture - /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/3.0/grpc_c.bundle
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
        from /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc.rb:19:in `require_relative'
        from /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/grpc-1.38.0-universal-darwin/src/ruby/lib/grpc.rb:19:in `<top (required)>'
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/lnrpc-0.13.0/lib/grpc_services/autopilotrpc/autopilot_services_pb.rb:4:in `<top (required)>'
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/lnrpc-0.13.0/lib/lnrpc.rb:5:in `block in <top (required)>'
        from /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/lnrpc-0.13.0/lib/lnrpc.rb:4:in `each'
        from /usr/local/var/rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/lnrpc-0.13.0/lib/lnrpc.rb:4:in `<top (required)>'
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from lnconnect.rb:1:in `<main>'
<internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- lnrpc (LoadError)
        from <internal:/usr/local/var/rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from lnconnect.rb:1:in `<main>'
```

**Comment by bumi** [comment]
are you sure you have the gem installed? and it is available? do you have a Gemfile? did you do gem install lnrpc?

**Comment by iraszl** [comment]
Thanks for following up. I do have a Gemfile and I use Bundle:
```
source 'https://rubygems.org'
ruby '3.0.1'
gem 'lnrpc', '~> 0.13.0'
```
```
bundle
Using bundler 2.2.16
Using google-protobuf 3.17.3 (universal-darwin)
Using googleapis-common-protos-types 1.1.0
Using grpc 1.38.0 (universal-darwin)
Using lnrpc 0.13.0
Bundle complete! 1 Gemfile dependency, 5 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
Any ideas on what could be wrong?

**Comment by bumi** [comment]
I think then you need to use bundler to require your dependencies.

and maybe run your script with bundle exec

**Comment by iraszl** [comment]
Thank you for your help and idea.

I think I narrowed it down to `grpc` to be the problem. It won't run outside of this gem either. And also I have the same issue on Intel macs as well. So it's not an M1 issue. I will try to resolve this first...

**Comment by bumi** [comment]
ok, thanks for the update.
I have not tested ruby 3 yet. will also look into it.
 
Ruby 2.7 should not be a problem.

**Comment by bumi** [comment]
sorry for the wrong thought with bundler and loading the dependency. 

I've just tested it on Ruby 3 and an M1 - it works for me. 

I am still wondering about the `LoadError` your are seeing. Could you debug this further?

**Comment by iraszl** [comment]
I can confirm everything works fine, as discussed elsewhere, adding address is required.

`lnd = Lnrpc::Client.new({
  credentials_path: '/doesn_need_to_be_secure/tls.cert',
  macaroon_path: '/keep_this_safe/keepitsafe.macaroon',
  address: 'yourserver.domain:10009'
})`
